# Generated by Django 5.1.7 on 2025-03-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
