# Generated by Django 5.1.7 on 2025-03-14 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_genre_bookgenre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atribute',
            new_name='Attribute',
        ),
        migrations.RenameModel(
            old_name='BookAtribute',
            new_name='BookAttribute',
        ),
        migrations.RenameField(
            model_name='bookattribute',
            old_name='atribute',
            new_name='attribute',
        ),
    ]
