# Generated by Django 5.1.7 on 2025-03-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_atribute_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='attributes',
            field=models.ManyToManyField(through='product.BookAttribute', to='product.attribute'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(through='product.BookGenre', to='product.genre'),
        ),
    ]
