# Generated by Django 5.1.7 on 2025-03-16 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_book_attributes_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value',
        ),
        migrations.CreateModel(
            name='BookAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=511)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='attributes',
            field=models.ManyToManyField(through='product.BookAttributeValue', to='product.attribute'),
        ),
        migrations.DeleteModel(
            name='BookAttribute',
        ),
    ]
