# Generated by Django 5.1.7 on 2025-03-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_fix_eav_model_of_book_and_attribute'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookattributevalue',
            constraint=models.UniqueConstraint(fields=('book', 'attribute'), name='unique_book_attribute_migration'),
        ),
    ]
