# Generated by Django 5.1.7 on 2025-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('product', '0009_bookattributevalue_unique_book_attribute_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='collections',
            field=models.ManyToManyField(through='collection.BookCollection', to='collection.collection'),
        ),
    ]
