# Generated by Django 5.1.7 on 2025-03-17 08:51

from django.db import migrations

attributes_name = ("ISBN", "Đối tượng", "Số trang", "Khuôn khổ", "Định dạng", "Số trang", "Trọng lượng", "Năm xuất bản")

def create_initial_collections(apps, schema_editor):
    Attribute = apps.get_model('product', 'Attribute')


    attributes = [
        Attribute(name=name) for name in attributes_name
    ]

    Attribute.objects.bulk_create(attributes)

def remove_initial_collections(apps, schema_editor):
    Attribute = apps.get_model('product', 'Attribute')
    Attribute.objects.filter(name__in=attributes_name).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_book_author_bookauthor_book_authors_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_collections, remove_initial_collections),
    ]
