# Generated by Django 5.1.8 on 2025-04-10 14:43

from datetime import datetime
from decimal import Decimal
from django.db import migrations

def migrate_eav_to_columns(apps, schema_editor):
    Book = apps.get_model('product', 'Book')
    BookAttributeValue = apps.get_model('product', 'BookAttributeValue')

    # Mapping of attribute names to new field names
    attribute_mapping = {
        "Năm xuất bản": "publish_year",
        "Trọng lượng": "weight",
        "Số trang": "page_count",
        "Định dạng": "format",
        "Khuôn khổ": "dimensions",
        "Đối tượng": "audience",
        "ISBN": "isbn",
    }

    for book in Book.objects.all():
        print(f"Processing book: {book.title}")
        # Get all attributes for the current book
        attributes = BookAttributeValue.objects.filter(book=book)

        for attribute in attributes:
            field_name = attribute_mapping.get(attribute.attribute.name)
            if field_name:
                if field_name == "weight":
                    value = Decimal(str(attribute.value).split(' ')[0])
                    setattr(book, field_name, value)
                elif field_name == "publish_year":
                    # Extract year from date string (e.g., "2024-04-16" -> 2024)
                    if len(attribute.value) == 4:
                        year = int(attribute.value)
                    else:
                        year = datetime.strptime(attribute.value, "%Y-%m-%d").year
                    setattr(book, field_name, year)
                elif field_name == "page_count":
                    # Extract number from string (e.g., "300 pages" -> 300)
                    page_count = int(attribute.value)
                    setattr(book, field_name, page_count)
                else:
                    # Set the corresponding field on the Book model
                    setattr(book, field_name, attribute.value)

        # Save the updated book
        book.save()

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_book_attributes_book_audience_book_dimensions_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_eav_to_columns),
    ]
