# Generated by Django 5.1.7 on 2025-03-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_bookattributevalue_unique_book_attribute_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('books', models.ManyToManyField(through='collection.BookCollection', to='product.book')),
            ],
        ),
        migrations.AddField(
            model_name='bookcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AddConstraint(
            model_name='bookcollection',
            constraint=models.UniqueConstraint(fields=('book', 'collection'), name='unique_book_collection_migration'),
        ),
    ]
