# Generated by Django 5.1.7 on 2025-03-17 02:31

from django.db import migrations, models

def create_initial_collections(apps, schema_editor):
    # Get the historical version of the model
    Collection = apps.get_model('collection', 'Collection')
    
    # Create your initial data
    collections = [
        Collection(
            name="Lịch sử, truyền thống",
            description="",
            slug="lich-su-truyen-thong"
        ),
        Collection(
            name="Văn học Việt Nam",
            description="",
            slug="van-hoc-viet-nam"
        ),
        Collection(
            name="Truyện tranh",
            description="",
            slug="truyen-tranh"
        ),
        Collection(
            name="Manga - Comic",
            description="",
            slug="manga-comic"
        ),
        Collection(
            name="Light Novel",
            description="",
            slug="light-novel"
        ),
        Collection(
            name="Kiến thức - Khoa học",
            description="",
            slug="kien-thuc-khoa-hoc"
        ),
    ]
    
    # Save all collections
    Collection.objects.bulk_create(collections)

def remove_initial_collections(apps, schema_editor):
    # Reverse operation (for migrations rollback)
    Collection = apps.get_model('collection', 'Collection')
    Collection.objects.filter(slug__in=['lich-su-truyen-thong', 'van-hoc-viet-nam', 'truyen-tranh', 'manga-comic', 'light-novel', 'kien-thuc-khoa-hoc']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(create_initial_collections, remove_initial_collections),
    ]
