# Generated by Django 5.1.7 on 2025-03-17 22:11

from django.db import migrations

blog_type_slugs = ["tin-tuc", "hoat-dong", "diem-sach", "su-kien"]

def create_initial_collections(apps, schema_editor):
    BlogType = apps.get_model('blog', 'BlogType')

    blog_types = [
        BlogType(name="Tin tức", slug="tin-tuc"),
        BlogType(name="Hoạt động", slug="hoat-dong"),
        BlogType(name="Điểm sách", slug="diem-sach"),
        BlogType(name="Sự kiện", slug="su-kien"),
    ]

    BlogType.objects.bulk_create(blog_types)

def remove_initial_collections(apps, schema_editor):
    BlogType = apps.get_model('blog', 'BlogType')
    BlogType.objects.filter(slug__in=blog_type_slugs).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_collections, remove_initial_collections),
    ]
