# Generated by Django 5.1.7 on 2025-03-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_initial_data_for_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_img',
            field=models.ImageField(blank=True, max_length=511, null=True, upload_to='blog/'),
        ),
    ]
