# Generated by Django 5.1.7 on 2025-03-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='blogs',
            field=models.ManyToManyField(related_name='blog_types', to='blog.blog'),
        ),
    ]
